### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by mecta02** [SUBLiME-Association/sublime_administration-fivem-esxLegacy#1]
Bonjour j'ai cette erreur . 

SCRIPT ERROR: ...tration/client/menu's/[c]MyPlayer/[b]MyPlayerOptions.lua:44: attempt to perform arithmetic on a nil value (field 'hunger')^7

aucune modif n'est apporter au script .

**Comment by SUP2Ak** [comment]
Salut tu ne doit pas avoir esx_status par defaut

**Comment by mecta02** [comment]
esx statut est bien start pourtant .

**Comment by SUP2Ak** [comment]
esx_basicneeds, c'est là que le le status hunger et thirst son enregistrer, il n'y pas de problème sur cela.
Donc tu as sans doute une version incompatible car il n'y a pas d'erreur là dessus

**Comment by mecta02** [comment]
effectivement petit bug dans la copie du esx_statuts .j'ai recopier est ces ok dsl du dérangement
