### ISSUE TITLE
job

### ISSUE THREAD

**Issue by mimiossart** [SUBLiME-Association/sublime_administration-fivem-esxLegacy#2]
la fonction setjob ne m'affiche rien aucun job est afficher

**Comment by SUP2Ak** [comment]
Salut, cette repo n'est plus archivé pour que les gens qui y veulent y contribué sont libre soient libre de le faire.
Et aussi car des personnes qui ont téléchargé le script par le passé ce sont amusé à le revendre ce qui fait qu'aujourd'hui "personnellement" j'apporterai aucune contribution personnel pour tout script liée à un framework tel que esx / qbcore

Mais sans plus d'information sur votre problème pour les gens qui verront votre issue cela sera compliqué de vous aidez.
